#Exercise 1:Create a numpy array containing the numbers from 1 to 10, and then reshape it to a 2x5 matrix

In [69]:
import numpy as np
a1=np.array([1,2,3,4,5,6,7,8,9,10])
print(a1)
new_array=a1.reshape(2,5)                   #reshape 
print(new_array)
print(new_array.shape)

[ 1  2  3  4  5  6  7  8  9 10]
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
(2, 5)


#Exercise 2:Create a numpy array containing the numbers from 1 to 20, and then extract the elements between the 5th and 15th index. 

In [71]:
array = np.arange(1, 21)
array
extracted_elements = array[5:15]
array, extracted_elements

(array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
        18, 19, 20]),
 array([ 6,  7,  8,  9, 10, 11, 12, 13, 14, 15]))

Exercise 3:Create a Pandas series with the following data: 
{'apples': 3, 'bananas': 2, 'oranges': 1}. Then, add a new item to the series with the key 'pears' and the value 4.

In [73]:
import pandas as pd 
fruits = pd.Series({'apples': 3, 'bananas': 2, 'oranges': 1})
print(fruits)
# Adding a new item 'pears' with the value 4
fruits['pears'] = 4
fruits

apples     3
bananas    2
oranges    1
dtype: int64


apples     3
bananas    2
oranges    1
pears      4
dtype: int64

#Exercise 4:Create a dataframe with the following columns: name, age, and gender. The dataframe should have 10 rows of data. 

In [91]:
import pandas as pd
import numpy as np

details= pd.DataFrame({
    'name': ["ajay","arun","sruthi","renju","afsal","sabith","jennifer","akash","kiran","vidhya"],
    'age': [26,25,24,30,45,25,35,25,24,29],
    'gender':["male","male","female","male","male","male","female","male","male","female"]
    },columns=['name','age','gender'])

details.index=[1,2,3,4,5,6,7,8,9,10]
details

name  age  gender
1       ajay   26    male
2       arun   25    male
3     sruthi   24  female
4      renju   30    male
5      afsal   45    male
6     sabith   25    male
7   jennifer   35  female
8      akash   25    male
9      kiran   24    male
10    vidhya   29  female

#Exercise 5:Add a new column to the data frame created in question 1, called occupation. 
The values for this column should be Programmer, Manager, and Analyst, corresponding to the rows in the dataframe.

In [93]:
details["Occupation"] = ["Programmer", "Manager", "Analyst","Developer","Senior analyst",
                         "Marketing manager","Junior developer","Programmer","System analyst","Business analyst"]
details

name  age  gender         Occupation
1       ajay   26    male         Programmer
2       arun   25    male            Manager
3     sruthi   24  female            Analyst
4      renju   30    male          Developer
5      afsal   45    male     Senior analyst
6     sabith   25    male  Marketing manager
7   jennifer   35  female   Junior developer
8      akash   25    male         Programmer
9      kiran   24    male     System analyst
10    vidhya   29  female   Business analyst

#Exercise 6: Select the rows of the dataframe where the age is greater than or equal to 30. 


In [95]:
details["age"]>=30

1     False
2     False
3     False
4      True
5      True
6     False
7      True
8     False
9     False
10    False
Name: age, dtype: bool

#Exercise 7:Convert this dataframe to a csv file and read that csv file, finally display the contents.

In [132]:
details.to_csv("final_details.csv")

data=pd.read_csv("final_details.csv")

In [134]:
details

name  age  gender         Occupation
1       ajay   26    male         Programmer
2       arun   25    male            Manager
3     sruthi   24  female            Analyst
4      renju   30    male          Developer
5      afsal   45    male     Senior analyst
6     sabith   25    male  Marketing manager
7   jennifer   35  female   Junior developer
8      akash   25    male         Programmer
9      kiran   24    male     System analyst
10    vidhya   29  female   Business analyst